assignemt 4
anaritarc/my-lp-foundations pull request #10
Opened 2023-05-29 17:23 UTC by anaritarc

2023-05-31 16:12 UTC, atneves reviewed
Good work :)

2023-05-31 16:12 UTC, atneves commented on life_expectancy/load_save_data.py
> +                data = json.load(json_file)
I think you can use pd.read_json with compression directly

2023-05-31 16:12 UTC, atneves commented on life_expectancy/pipeline.py
> +        'csv': LoadCsvStrategy()
Maybe you can do a dictionary like this : 
strategies = {
        'json': LoadJsonStrategy,
        'csv': LoadCsvStrategy
}
and only instatiate the classes when you need it

2023-05-31 16:12 UTC, atneves commented on life_expectancy/tests/test_load_save_data.py
> +    assert isinstance(result, pd.DataFrame)
you can assert it is not null too

2023-05-31 16:12 UTC, atneves commented on life_expectancy/tests/test_load_save_data.py
> +    result = LoadCsvStrategy().load_data()
I think it is possible to join this 2 load tests in one using @pytest.mark.parametrize

2023-05-31 16:12 UTC, atneves reviewed
Good work :)

2023-06-01 16:32 UTC, MrCordeiro requested changes

2023-06-01 16:32 UTC, MrCordeiro commented on life_expectancy/tests/test_pipeline.py
> +        mock_load_data = MagicMock()
**Suggestion** Try running without this

2023-06-01 16:32 UTC, MrCordeiro commented on life_expectancy/tests/test_pipeline.py
> +        main(args.region, args.json_csv)
```suggestion
        main('pt', 'json')
```

2023-06-01 16:32 UTC, MrCordeiro commented on life_expectancy/tests/conftest.py
> +            return pd.read_json(json_data)
```suggestion
     return pd.read_json(zip_file_path, compression="infer")
```

2023-06-01 16:32 UTC, MrCordeiro commented on life_expectancy/tests/conftest.py
> +import zipfile
```suggestion
```

2023-06-01 16:32 UTC, MrCordeiro commented on life_expectancy/pipeline.py
> +        'json': LoadJsonStrategy(),
`LoadZippedJsonStrategy`

If you receive a Path, you can use Path.suffix to extract your strategy key

2023-06-01 16:32 UTC, MrCordeiro commented on life_expectancy/pipeline.py
> +    Russia = 'RU'
Missing method to return all contry values as list of strings

2023-06-01 16:32 UTC, MrCordeiro commented on life_expectancy/pipeline.py
> +        type=Country, choices=list(Country),
Validate if list(Country) return a list of string

2023-06-01 16:32 UTC, MrCordeiro commented on life_expectancy/load_save_data.py
> +def save_data(df, region) -> None:
Missing type hints

2023-06-01 16:32 UTC, MrCordeiro commented on life_expectancy/pipeline.py
> +def main(region='pt', json_csv='csv') -> None:
Should main be receiving a string or a Region?

2024-10-20 10:47 UTC, closed without merging